### ISSUE TITLE
Kupić 2 żarówki

### ISSUE THREAD

**Issue by KindOfBluee** [KindOfBluee/PiLightbulb#1]
Z wyjściem GU5.3, minimum 450 LM

**Comment by KindOfBluee** [comment]
https://led-hurt.pl/pl/p/Zarowka-LED-MR16-GU5%2C3-5W-230V-SMD2835-biala-naturalna/1829

**Comment by kacperkapusciak** [comment]
https://www.castorama.pl/produkty/urzadzanie/zarowki-i-swietlowki/zarowki-led/zarowka-led-opp-a60-5-8-w-e27-470-lm-mleczna-barwa-ciepla-4-szt.html
https://www.castorama.pl/produkty/urzadzanie/lampy-oswietlenie/akcesoria-do-oswietlenia/oprawki-z-kablem/oprawka-remontowa-wiwa-opr-01.html
